### PR TITLE
update_maintainers

### PR DESCRIPTION
**Pull request by PedroDiez**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Update maintainers

#### Which issue(s) this PR fixes:

Fixes Issue https://github.com/camaraproject/BlockchainPublicAddress/issues/10

### CODE REVIEW

**Comment by MarkusKuemmerle** [comment]
Please make sure that all new maintainers are part of the Sub Project before accepting and merging this pull request. Klaus is missing in the moment.

**Comment by PedroDiez** [comment]
> Please make sure that all new maintainers are part of the Sub Project before accepting and merging this pull request. Klaus is missing in the moment.

Yes, we are waiting for klaus having access before merging it

**Comment by PedroDiez** [comment]
Remove Klaus so far.

Ready to be review and merged

**Review by sebKoeller — APPROVED** [review]

**Review by jordonezlucena — APPROVED** [review]
LGTM

**Pull request merged**
