### PR TITLE
Update Codeowners: Remove Sebastian and Jose Antonio and Add Krzysztof

### PR DESCRIPTION
**Pull request by PedroDiez**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Remove Sebastian as no longer participating in the WG
Remove Jose Antonio as not involved in technical track
Add Krzysztof as enabled his subscription

### CODE REVIEW

**Review by sebKoeller — DISMISSED** [review]

**Review by jordonezlucena — APPROVED** [review]
/LGTM

**Review by sebKoeller — APPROVED** [review]

**Comment by PedroDiez** [comment]
Need to check as file indicates Krzysztof has not write access to repository

@ksl4dtit have you checked your access?

**Comment by PedroDiez** [comment]
To be safety, if no certainty about Krzysztof tomorrow i will update PR just to remove Sebastian and Jose Antonio

**Comment by MarkusKuemmerle** [comment]
I've provided writing permissions to Krzysztof, you now can merge this PR. I'll then remove the permissions for Sebastian and Jose.

**Comment by PedroDiez** [comment]
Thanks Markus!

**Pull request merged**
