### PR TITLE
create_changelog_release_v010

### PR DESCRIPTION
**Pull request by PedroDiez**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Update of CHANGELOG.md for the release v0.1.0

The merge commit of this PR will be tagged as release v0.1.0

#### Which issue(s) this PR fixes:

Fixes [#22](https://github.com/camaraproject/BlockchainPublicAddress/issues/22)

#### Special notes for reviewers:

N/A

### CODE REVIEW

**Review by grgpapadopoulos — APPROVED** [review]

**Review by sebKoeller — APPROVED** [review]

**Comment by PedroDiez** [comment]
Seb, Georgios just to kindly ask the approval again as codeowners

**Comment by grgpapadopoulos** [comment]
Hello @PedroDiez, 
the Changelog link https://github.com/camaraproject/BlockchainPublicAddress/commits/v0.1.0 
returns a 404 to me

**Comment by PedroDiez** [comment]
> Hello @PedroDiez, the Changelog link https://github.com/camaraproject/BlockchainPublicAddress/commits/v0.1.0 returns a 404 to me

I think it will work after merging this PR and afterwards generating the tag/release, isn't it @rartych?

**Review by grgpapadopoulos — APPROVED** [review]
lets find out

**Review by rartych — APPROVED** [review]
It should work after publishing the release.

**Review by sebKoeller — APPROVED** [review]

**Comment by PedroDiez** [comment]
Thanks guys!!!! Let's go then

**Pull request merged**
