### PR TITLE
baseline_proposal_v010

### PR DESCRIPTION
**Pull request by PedroDiez**
## PR

Initial Baseline proposal for discussion

Pending Points in API Evolution identified so far:
* Model for "currency" is open topic for long-term solution
* Model for "blockchain" is also to be discussed
* Pending Considerations about Consent Management

Some refinements covered in v0.1.0, as commented in 2023-08-31 meeting (agreed to be merged as initial proposal to have a baseline)

* Editorials:
> - version: "0.1.0"
> - "phone_number" renamed to "phone number" in descriptive information
> - Aligned with commonalities some parameters name and examples to be camelCase. https://github.com/camaraproject/Commonalities/blob/main/documentation/API-design-guidelines.md#42-inputoutput-resource-definition
> - Aligned "phoneNumber" description format (taking same wording as in QoD API -> "_In order to be globally unique it has to be formatted in international format, according to E.164 standard, optionally prefixed with '+'_.")

### CODE REVIEW

**Comment by rartych** [comment]
There is "_OB_" abbreviation used in embedded documentation (and "_OB network_" expression) that is unclear for me.
It was explained in this comment:
https://github.com/camaraproject/WorkingGroups/pull/154#issuecomment-1458649342
Anyway, it should be replaced by other expression like _Operator_ or _Telco Operator_.

**Comment by PedroDiez** [comment]
> There is "_OB_" abbreviation used in embedded documentation (and "_OB network_" expression) that is unclear for me. It was explained in this comment: [camaraproject/WorkingGroups#154 (comment)](https://github.com/camaraproject/WorkingGroups/pull/154#issuecomment-1458649342) Anyway, it should be replaced by other expression like _Operator_ or _Telco Operator_.

>> Thanks Rafal. Take note to update this in the PR

**Comment by PedroDiez** [comment]
NOTE: Pending to update image reference

**Comment by PedroDiez** [comment]
11/AGO: Changes Summary

- Renamed OB to Telco Operator
- Adding Exception 429
- Removed Image Reference So Far

In Discussion:
- Currency Concept [Issue#12](https://github.com/camaraproject/BlockchainPublicAddress/issues/12)

Pending:
- Impact in API about handling of Consent Management

**Review by grgpapadopoulos — APPROVED** [review]

**Review by sebKoeller — APPROVED** [review]
I think it's important that we finally have a first version of our API specification.
Let's settle for this version first, and then we add our improvements over time.

**Comment by PedroDiez** [comment]
Agree @sebKoeller @grgpapadopoulos 

I will do some refinements and clearly state here: (and in PR description)

* Model for "currency" is open topic for long-term solution
* Model for "blockchain" is also to be discussed
* Pending Considerations about Consent Management

**Comment by PedroDiez** [comment]
Please, @grgpapadopoulos @sebKoeller take a look to the refinements.

**Review by sebKoeller — APPROVED** [review]
Thanks for the update @PedroDiez.
lgtm

**Review by jordonezlucena — APPROVED** [review]
LGTM

**Pull request merged**
