### PR TITLE
update_codeowners

### PR DESCRIPTION
**Pull request by PedroDiez**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Update Codeowners

#### Which issue(s) this PR fixes:

Fixes Issue https://github.com/camaraproject/BlockchainPublicAddress/issues/10

### CODE REVIEW

**Review by jordonezlucena — APPROVED** [review]

**Comment by MarkusKuemmerle** [comment]
@jordonezlucena @PedroDiez : Please make sure that all new codeowners are part of the Sub Project before merging such a PR. Klaus is missing in the moment, so the Codeowners file is not valid!

**Comment by PedroDiez** [comment]
> @jordonezlucena @PedroDiez : Please make sure that all new codeowners are part of the Sub Project before merging such a PR. Klaus is missing in the moment, so the Codeowners file is not valid!

@MarkusKuemmerle  I was aware of that, but wanted to trigger in advance. Once they become members, this config file will apply and we will see them as effective codeowners, isn't?

**Comment by MarkusKuemmerle** [comment]
@pedrodiez : The Codeowners file is a technical file used by some tools automatically. If it‘s invalid this tools don‘t work. So we should care about having a valid file all the time
sent with Telekom-IT Corporate Mobile Service
Am 11. August 2023 um 15:41:39 MESZ schrieb Pedro Díez García ***@***.***>:

@jordonezlucena<https://github.com/jordonezlucena> @PedroDiez<https://github.com/PedroDiez> : Please make sure that all new codeowners are part of the Sub Project before merging such a PR. Klaus is missing in the moment, so the Codeowners file is not valid!

@MarkusKuemmerle<https://github.com/MarkusKuemmerle> I was aware of that, but wanted to trigger in advance. Once they become members, this config file will apply and we will see them as effective codeowners, isn't?

**Comment by PedroDiez** [comment]
Ok Markus I revert change now in a new PR

**Pull request merged**
